### ISSUE TITLE
Publish, Client, Documentation - model-psp [4.5pt]

### ISSUE THREAD

**Issue by nilssonemma** [Intergiro/model#367]
- [ ] Rename and publish [0.5pt]
- [x] Create a Client [2pt]
- [x] Read through documentation, make sure examples work, create postman/insomnia scripts [2pt]
